### ISSUE TITLE
findById and existsById throwing exception

### ISSUE THREAD

**Issue by surjitbhachu** [spring-projects/spring-data-neo4j#2419] opened 2021-11-01 19:03 UTC
I am trying to upgrade Spring Neo4j 6.1.5 to 6.1.6.

Here is my entity class:

```
@Node("Entity")
@Data
public class Entity {

    @Id
    @GeneratedValue(UUIDStringGenerator.class)
    private String id;
    
    private String key;

    private String name;

    private String description;

    private String[] aliases;

    private String createdBy;

    private String lastModifiedBy;

    @CompositeProperty
    private Map<String, String> sources;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    private ZonedDateTime createdDate;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    private ZonedDateTime lastModifiedDate;

    @DynamicLabels
    private List<String> labels = new ArrayList<>();
    
    @CompositeProperty
    private Map<String, String> properties;

    @Relationship
    private Map<String, List<RelatedEntity>> relatedEntities = new HashMap<>();
}

```

When I try to run the method `findById` or `existsById`, I get the following exception:

```
2021-11-01 18:54:46.347  WARN 73733 --- [o4jDriverIO-2-2] org.neo4j.driver.ChannelErrorHandler     : [0x48639be0][localhost:7687][bolt-534] Fatal error occurred in the pipeline

org.neo4j.driver.exceptions.DatabaseException: Expected 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['  rootNodeIds@7'], Predicates: ['id(`  rootNodeIds@7`) IN $rootNodeIds']},InterestingOrder(RequiredOrderCandidate(List()),List(InterestingOrderCandidate(List(Asc(Variable(  n@87),Map()))), InterestingOrderCandidate(List(Desc(Variable(  n@87),Map()))))),AggregatingQueryProjection(Map(),Map(  n@87 -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87'], Optional Matches: : ['QueryGraph {Rels: ['(  NODE104(79db9ebc-7ed3-4415-aca6-c72e4f85487e))-[relationshipIds]-(  NODE125(00a998c2-7b02-4bc2-aa4c-94685207d964))'], Predicates: ['id(relationshipIds) IN $relationshipIds']}']},InterestingOrder(RequiredOrderCandidate(List()),List(InterestingOrderCandidate(List(Asc(Variable(  n@87),Map()))), InterestingOrderCandidate(List(Desc(Variable(  n@87),Map()))))),AggregatingQueryProjection(Map(  n@87 -> Variable(  n@87)),Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '__sr__'], Optional Matches: : ['QueryGraph {Nodes: ['relatedNodeIds'], Predicates: ['id(relatedNodeIds) IN $relatedNodeIds']}']},InterestingOrder(RequiredOrderCandidate(List()),List(InterestingOrderCandidate(List(Asc(Variable(  n@87),Map()))), InterestingOrderCandidate(List(Desc(Variable(  n@87),Map()))), InterestingOrderCandidate(List(Asc(Variable(__sr__),Map()))), InterestingOrderCandidate(List(Desc(Variable(__sr__),Map()))))),AggregatingQueryProjection(Map(  n@87 -> Variable(  n@87), __sr__ -> Variable(__sr__)),Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),UnwindProjection(  rootNodeIds@384,Variable(  n@87)),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '  rootNodeIds@384', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(  n@416 -> Variable(  rootNodeIds@384), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@416', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(__sn__ -> Variable(  n@416), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryPagination(None,None),Selections(Set())),None,None)),None)),None)),None)),None)),None) 


Instead, got: 
RegularSinglePlannerQuery(QueryGraph {Nodes: ['  rootNodeIds@7'], Predicates: ['id(`  rootNodeIds@7`) IN $rootNodeIds']},InterestingOrder(RequiredOrderCandidate(List()),List()),AggregatingQueryProjection(Map(),Map(  n@87 -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87'], Optional Matches: : ['QueryGraph {}']},InterestingOrder(RequiredOrderCandidate(List()),List()),AggregatingQueryProjection(Map(  n@87 -> Variable(  n@87)),Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '__sr__'], Optional Matches: : ['QueryGraph {Nodes: ['relatedNodeIds'], Predicates: ['id(relatedNodeIds) IN $relatedNodeIds']}']},InterestingOrder(RequiredOrderCandidate(List()),List()),AggregatingQueryProjection(Map(  n@87 -> Variable(  n@87), __sr__ -> Variable(__sr__)),Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds)))),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),UnwindProjection(  rootNodeIds@384,Variable(  n@87)),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@87', '  rootNodeIds@384', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(  n@416 -> Variable(  rootNodeIds@384), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryPagination(None,None),Selections(Set())),Some(RegularSinglePlannerQuery(QueryGraph {Arguments: ['  n@416', '__sr__', '__srn__']},InterestingOrder(RequiredOrderCandidate(List()),List()),RegularQueryProjection(Map(__sn__ -> Variable(  n@416), __sr__ -> Variable(__sr__), __srn__ -> Variable(__srn__)),QueryPagination(None,None),Selections(Set())),None,None)),None)),None)),None)),None)),None)
Plan: ProduceResult(List(__sn__, __sr__, __srn__)) {
  LHS -> Projection(Map(__sn__ -> Variable(  n@416))) {
    LHS -> Apply(false) {
      LHS -> Projection(Map(  n@416 -> Variable(  rootNodeIds@384))) {
        LHS -> Apply(false) {
          LHS -> UnwindCollection(  rootNodeIds@384, Variable(  n@87)) {
            LHS -> Apply(false) {
              LHS -> Aggregation(Map(  n@87 -> Variable(  n@87), __sr__ -> Variable(__sr__)), Map(__srn__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relatedNodeIds))))) {
                LHS -> Apply(false) {
                  LHS -> Aggregation(Map(  n@87 -> Variable(  n@87)), Map(__sr__ -> FunctionInvocation(Namespace(List()),FunctionName(collect),true,Vector(Variable(relationshipIds))))) {
                    LHS -> Apply(false) {
                      LHS -> Aggregation(Map(), Map(  n@87 -> FunctionInvocation(Namespace(List()),FunctionName(collect),false,Vector(Variable(  rootNodeIds@7))))) {
                        LHS -> Selection(Ands(Vector(In(FunctionInvocation(Namespace(List()),FunctionName(id),false,Vector(Variable(  rootNodeIds@7))),ExplicitParameter(rootNodeIds,List<Any>))))) {
                          LHS -> AllNodesScan(  rootNodeIds@7, Set()) {}
                        }
                      }
                      RHS -> Apply(false) {
                        LHS -> Argument(Set(  n@87)) {}
                        RHS -> Optional(Set(  n@87)) {
                          LHS -> Argument(Set()) {}
                        }
                      }
                    }
                  }
                  RHS -> Apply(false) {
                    LHS -> Argument(Set(  n@87, __sr__)) {}
                    RHS -> Optional(Set(  n@87, __sr__)) {
                      LHS -> Selection(Ands(Vector(In(FunctionInvocation(Namespace(List()),FunctionName(id),false,Vector(Variable(relatedNodeIds))),ExplicitParameter(relatedNodeIds,List<Any>))))) {
                        LHS -> AllNodesScan(relatedNodeIds, Set()) {}
                      }
                    }
                  }
                }
              }
              RHS -> Argument(Set(  n@87, __sr__, __srn__)) {}
            }
          }
          RHS -> Argument(Set(  n@87, __sr__, __srn__,   rootNodeIds@384)) {}
        }
      }
      RHS -> Argument(Set(  n@416, __sr__, __srn__)) {}
    }
  }
} 

.... 
```
If I revert back to 6.1.5, I don't get the exception.

**Comment by meistermeier** [comment] 2021-11-02 07:59
Thanks for reporting this.
We had to improve the statements for handling cyclic domains.
What you are seeing is a bug in the product (Cypher planner) itself and is solved in 4.3.3 / 4.2.10 (or higher).
Our advice is to upgrade to the newest patch versions.

Duplicate of https://github.com/spring-projects/spring-data-neo4j/issues/2414

**Closed by meistermeier** 2021-11-02 07:59 UTC
Labels: status: waiting-for-triage
