### ISSUE TITLE
toString id clashes with parameters of type Long (SDN 7.1.3/7.1.4)

### ISSUE THREAD

**Issue by sobczynskipio** [spring-projects/spring-data-neo4j#2872] opened 2024-03-13 08:23 UTC
Hi, seems like I've found one bug which really blocks stepping of SDN in my project (springboot 3.1.3 -> 3.1.4):

There's been a change between SDN 7.1.3 and 7.1.4 which made method name derived queries return empty results for entities marked as **containsPossibleCircles** in Neo4jTemplate.

In Neo4jTemplate class, there's a **TemplateSupport.convertToLongIdOrStringElementId(nodeIds)** invocation which makes query params of type Long always NOT match with entity nodeIds. See screenshot attached. SDN logic somehow get's there only for entities for which **containsPossibleCircles** is set to true in Neo4jTemplate. My entities don't really contain circles in relationships but this probably does not matter. Repository methods like findAll or findById always give empty results for those cause SDN compares stringified ids with Long params. It works in SDN 7.1.3 and is broken in 7.1.4 and later

Regards !

![SDN-ids-issue](https://github.com/spring-projects/spring-data-neo4j/assets/19777673/956591ec-47b2-4ca0-b231-b3ddfac27863)

**Comment by sobczynskipio** [comment] 2024-03-14 10:01
Of course, going through the SDN code I can see you check for those possibleCircles, that's why in my code the issue applies only to a subset of entities. I can share one of the simpler ones. Please see the screenshots attached. This entity is part of a linked list cause it has a relationship to **previous** of the same type. My logic prevents pointing at the very same object, it's just a linked list of objects of the same type so we keep a relationship to the previous one.

![Screenshot 2024-03-14 at 10 55 41](https://github.com/spring-projects/spring-data-neo4j/assets/19777673/2e9aa337-8ee3-43e4-89f5-26b6c59fb928)

Feels like it's ok to have an entity with possibleCircles. The reason is why only in this case we compare stringified ids with Long params for methods like findAll, finbById and so on.

**Comment by sobczynskipio** [comment] 2024-03-14 10:09
In that case above, with repository defined as here (see screenshot), querying **userChangesRepository.findAll()** gives out an empty result even though there are many nodes of a kind in the DB
![Screenshot 2024-03-14 at 11 08 17](https://github.com/spring-projects/spring-data-neo4j/assets/19777673/b7236d81-3a04-46cd-9902-a43bffbc87ba)

**Comment by michael-simons** [comment] 2024-03-14 10:12
Can I see your `Entity` definition, pls?

**Comment by sobczynskipio** [comment] 2024-03-14 10:14
Sure.
![Screenshot 2024-03-14 at 11 13 14](https://github.com/spring-projects/spring-data-neo4j/assets/19777673/f395ce1d-496e-43c4-a2be-e662cfc11cbb)
![Screenshot 2024-03-14 at 11 13 28](https://github.com/spring-projects/spring-data-neo4j/assets/19777673/d2188e7e-66a4-48da-8100-382577faceed)

 I may be having a redundant getNodeId method here, I know.

**Comment by michael-simons** [comment] 2024-03-14 11:04
I cannot reproduce this, see linked PR.

Make sure you configure the Cypher-DSL dialect, pls

https://docs.spring.io/spring-data/neo4j/reference/getting-started.html#configure-cypher-dsl-dialect

I tried both the main branch and the current 7.1.x branch.

**Comment by sobczynskipio** [comment] 2024-03-14 12:04
Thank you for your effort, let me see if I can provide simpliest (not)working runnable example. Let's leave this ticket hanging for a moment more please.

**Comment by michael-simons** [comment] 2024-03-14 12:05
Ofc, feel free to take my branch as a working base.

**Comment by sobczynskipio** [comment] 2024-03-15 08:25
Ok, I downloaded the branch and run your passing tests. My first observation, the test doesn't even reach 		
public Collection<T> all() {...} in DefaultNeo4jClient class like it does in my case. I'm looking into it why but maybe you could speed things up a notch. Seems like findAll takes completely different path in the code in your case

**Comment by sobczynskipio** [comment] 2024-03-18 07:42
Hey, apparently what solved my issue was downgrading cypherdsl to **2023.2.0** That's what is used in your branch Michael. There's no toString methods performed on entity nodeIds there. I think we can close this issue. Still I'll need to keep my eyes out next time when I need to step versions and cypherdsl. Maybe worth looking at from your side at one point ?

Regards

**Comment by michael-simons** [comment] 2024-03-18 09:16
Hey, thanks for your detailed feedback so far.
Now I would like to keep this open for further investigation (I'm just juggling a bit with time atm).

Thank!!

**Comment by sobczynskipio** [comment] 2024-03-18 09:18
No worries, feel free to contact me for more details if needed. Cheers.

**Comment by meistermeier** [comment] 2024-08-01 07:30
The issue is now unrelated to Spring Data Neo4j and points towards an rather old version of the CypherDSL.
Closing this issue.

**Closed by meistermeier** 2024-08-01 07:30 UTC
Labels: status: waiting-for-triage
