### ISSUE TITLE
Kotlin polymorphism with data classes seems impossible 

### ISSUE THREAD

**Issue by frederic-kneier** [spring-projects/spring-data-neo4j#2532] opened 2022-05-03 14:39 UTC
I'm currently unable to query for nodes using a base class or interface. If using an interface I get an error telling me the entity is unknown.

Using a abstract class neo4j does not recognize the id field of the base class unless it is not abstract. Having a non abstract id field makes using this abstract class as a base for a derived kotlin data class.

The mapping annotations should be targeted to and looked up op getter methods also to allow defining mapping to abstract properties.

For now I found a workaround that uses the mapping function for prepared statements to determine the actual mapping function for the concrete implementation of a base interface based on the labels found on the actual node being returned.

Currently the does not seem to be a good way to do polymorphic queries using kotlin data classes.

**Comment by meistermeier** [comment] 2022-05-04 06:51
Thanks for reporting this. We are happy to investigate on this, if you could provide a small reproducer for your problem. For now it's too much guessing e.g. on which level the (abstract) classes are annotated with `@Node` etc.
I would guess that the problem is somewhere to find in the second paragraph (either on our or your side), but I am not sure.

**Comment by spring-projects-issues** [comment] 2022-05-11 06:55
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-05-18 06:55
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-05-18 06:55 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
