### ISSUE TITLE
Neo4J database connectivity is lost after idle timeout

### ISSUE THREAD

**Issue by sbsatter** [spring-projects/spring-data-neo4j#2513] opened 2022-03-25 21:55 UTC
Hi, thank you for this amazing project.

I am working with @Query annotation to pass custom queries, make APOC calls to Neo4J (using bolt based neo4j java driver). 
After some idle timeout, I am seeing that connection is lost to Neo4J, and API calls to Spring Boot results into a long time loading (which finally resolves to status 500).

On multiple cases, I have found that after running my SB application (or after a successful query), the log below appears exactly 2 hours 10 mins later (on 2 occasions). In other cases, I have found that querying (say after 10/15 mins) yield the same exception: `[0x626e54ba][20.101.87.203:7687][bolt-33070] Fatal error occurred in the pipeline`. 

In other cases, it works after the same durations.

I am trying to understand if this is a bug, or a configuration not in place yet. I am looking to understand how to resolve this issue.

Env:
SDN 6.1.9
Neo4J Java Driver 4.2.9 (from SDN)
Neo4j Server version: [4.3.2] Community Edition (hosted on Azure VM, single instance)

Please note the occurrence of logs below. Last successful result was executed at `2022-03-26 00:25:34.357 ` and error issued 2 hr 10 mins later when left running in an idle pc with no interactions.

```
2022-03-26 00:25:34.357  INFO 8719 --- [o4jDriverIO-2-7] reactor.Mono.StreamCollector.6           : | onComplete()
2022-03-26 02:35:34.048  WARN 8719 --- [o4jDriverIO-2-6] org.neo4j.driver.ChannelErrorHandler     : [0xb8a924ac][20.101.87.203:7687][bolt-33068] Fatal error occurred in the pipeline

java.io.IOException: Operation timed out
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-03-26 02:35:34.370  WARN 8719 --- [o4jDriverIO-2-8] org.neo4j.driver.ChannelErrorHandler     : [0x626e54ba][20.101.87.203:7687][bolt-33070] Fatal error occurred in the pipeline

java.io.IOException: Operation timed out
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2022-03-26 02:35:34.606  WARN 8719 --- [o4jDriverIO-2-7] org.neo4j.driver.ChannelErrorHandler     : [0x3f506b92][20.101.87.203:7687][bolt-33069] Fatal error occurred in the pipeline

java.io.IOException: Operation timed out
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[na:na]
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[na:na]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.2.9.jar:4.2.9-d38816bdf6b220224312618acb44959ade25a3e6]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]


```

Any suggestions/workaround is welcome.

**Comment by meistermeier** [comment] 2022-03-28 09:39
Can you reproduce the issue with the Neo4j Java driver alone? It looks to me that SDN is not the responsible layer for this problem. If you can, it would be helpful to raise the issue there https://github.com/neo4j/neo4j-java-driver/issues
Unfortunately I cannot transfer the issue because the repositories belong to different orgs.
I close the issue now because I cannot see any point where we can help you here. Also there different config options for the driver that the good people of the Neo4j driver team are more experienced with than we. If you have any insights why SDN is part of the problem, feel free to re-open the issue.

**Closed by meistermeier** 2022-03-28 09:39 UTC
Labels: status: waiting-for-triage
