### ISSUE TITLE
Neo4jRepository.save() cannot update the node

### ISSUE THREAD

**Issue by Lishuaihu-222613** [spring-projects/spring-data-neo4j#2680] opened 2023-02-21 11:53 UTC
When I use the Neo4jRepository.save() to update an object, it cannot modify the attritube of the node, and it will create a new node. The 
modify node object's id is same as the original node, but it seems cannot distinguish them. I don't know how to modify the attritube of node.Here is the entity which I want to create 
[Material.zip](https://github.com/spring-projects/spring-data-neo4j/files/10793181/Material.zip)
and modify.

**Comment by meistermeier** [comment] 2023-02-23 13:03
Do you have any code that shows the interaction. I would say, if you really have copied `materialId` and `materialName`, SDN will see this as the same object and use the properties of the one you provide for the save call.

**Comment by Lishuaihu-222613** [comment] 2023-02-28 09:03
ok, here is the interaction code.
 public Material updateMaterial(Material newMaterial) {
        Long materialId = newMaterial.getMaterialId();
        Material oldMaterial = materialRepository.findById(materialId).get();
        oldMaterial.setMaterialName(newMaterial.getMaterialName());
        oldMaterial.setEnglishName(newMaterial.getEnglishName());
        oldMaterial.setNickName(newMaterial.getNickName());
        oldMaterial.setEnglishNickName(newMaterial.getEnglishNickName());
        oldMaterial.setRelativeMolecularMass(newMaterial.getRelativeMolecularMass());
        oldMaterial.setStructuralFormula(newMaterial.getStructuralFormula());
        oldMaterial.setCasRegistryNumber(newMaterial.getCasRegistryNumber());
        oldMaterial.setMaterialAppearance(newMaterial.getMaterialAppearance());
        oldMaterial.setMaterialDescription(newMaterial.getMaterialDescription());
        oldMaterial.setMaterialUsage(newMaterial.getMaterialUsage());
        oldMaterial.setMaterialLabels(newMaterial.getMaterialLabels());
        return materialRepository.save(oldMaterial);
    }

**Comment by meistermeier** [comment] 2023-03-01 10:14
I reduced the example a little bit but it should in general represent your data: https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2680
There is a test inside that runs perfectly fine and does not duplicate the `Material` on save.
Would be helpful to know what else could be different or the cause of your problem.

**Comment by spring-projects-issues** [comment] 2023-03-08 10:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-03-15 10:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-03-15 10:18 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
