### ISSUE TITLE
After Update to Spring Boot 2.4.1 , not able to fetch parent Object using custom query [DATAGRAPH-1473]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#2034] opened 2020-12-30 10:48 UTC
**[wolfy027](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50834)** opened **[DATAGRAPH-1473](https://jira.spring.io/browse/DATAGRAPH-1473?redirect=false)** and commented

Custom Query used in AnimalRepository > `@Query`: 

 

```java
MATCH path=(n:Animal {uuid: $id})-[:`PARENT`*0..]->() RETURN path
```

Spring Boot Version before update : 2.3.4

Spring Boot Version before update : 2.4.1

 

Domain reference:

 

```java
@Node
@JsonSerialize(as = Animal.class)
@JsonDeserialize(as = Animal.class)
public class Animal{
@Id
@GeneratedValue(generatorClass = GeneratedValue.UUIDGenerator.class)
private UUID uuid;
 
@Relationship(type = "PARENT", direction = Relationship.Direction.OUTGOING)
private Animal parent;
..
..
}
```

 

 

All the other properties are parsed except for parent which is null for any animal.

 

 

---

**Affects:** 6.0.2 (2020.0.2)

**Comment by robin850** [comment] 2021-01-06 15:59
Hello,

I had a similar issue. Basically, with something like this:

~~~java
@Node
class Technology {
    private String name;
}
~~~

~~~java
@Node
class Application {
    @Relationship("RELIES_ON")
    private List<Technology> technologies;
}
~~~

Then, on the repository side, trying to fetch an application and its technologies would return the application but with an empty set of technologies:

~~~java
@Query("MATCH (a:Application)" +
        " OPTIONAL MATCH (a)-[r:RELIES_ON]->(t:Technology)" +
        " RETURN a, r, t")
List<Application> fooBar(String name);
~~~

It can be fixed this by using `COLLECT(r), COLLECT(t)`. Fetching and collecting the relationship part (even though it is not mapped to an `@RelationshipProperties` class) is **important** ; the list is empty with only `COLLECT(t)` even though that's what matters here.

I don't know if it is expected or not but maybe the documentation could be improve at this level as there seems to be behavioral differences between the previous SDN/OGM and SDN 6 regarding relationships.

**Comment by meistermeier** [comment] 2021-01-07 08:49
You are right in both cases @robin850: You need to make use of the `COLLECT` function in order to provide a single result in contrast to a cartesian product. And yes, this is for sure some documentation missing on this bit. There is already an issue for this, so I will close this issue as it now is only a duplicate of #2032

**Closed by meistermeier** 2021-01-07 08:49 UTC
Labels: in: core, type: bug

**Comment by wolfy027** [comment] 2021-01-18 11:59
Thanks, the issue got solved with the updated query suggested by @robin850

**Comment by wolfy027** [comment] 2021-01-18 14:53
`MATCH (c:Animal {uuid: $id})  OPTIONAL MATCH (c)-[r:PARENT]->(p:Animal) RETURN p,collect(r),collect(p)`

This gives me response with attributes of current node and it's parent's nodes, but it skips the grand-parent's attributes. 

`MATCH (c:Animal {uuid: $id})  OPTIONAL MATCH (c)-[r:PARENT*]->(p:Animal) RETURN p,collect(r),collect(p)` does'nt work

What should be the suggested change?  @robin850 @meistermeier

**Comment by meistermeier** [comment] 2021-01-19 07:59
Before I open up a new issue on this one: Could you set the SDN version to 6.0.3 in your pom?
There were several fixes targeting inheritance.
