### ISSUE TITLE
@Transactional not working

### ISSUE THREAD

**Issue by shayantabrizi** [spring-projects/spring-data-neo4j#2268] opened 2021-05-30 13:19 UTC
I have a simple Spring Boot project with Neo4j SDN (v6.1.1). The problem is that when I mark a method with @Transactional, it seems that it does not consider that (as opposed to when I used Neo4j-OGM and a previous version of SDN). When I checked the database after "template.save", the update was visible in the database, even before the whole method is run. What should I do?

The method:

    @Transactional
    void method() {
            template.deleteAll(Person.class);
            template.deleteAll(Club.class);
            // save by Neo4jTemplate
            Person person_1 = template.save(new Person("Reza", "Mahdavi", 22, new Member(new Club("Iran"), "2021")));
            // Save by Repository
            Person person_2 = repository.save(new Person("Ali" + new Random(System.currentTimeMillis()).nextInt(), "Alavi", 20, new Member(new Club("Iran"), "2020")));
            // Query by Repository
            Person ali = repository.findByName("Ali");
            // Query by Neo4jTemplate
            Optional<Person> reza = template.findById(person_1.getId(), Person.class);
            // Custom query
            Result result = driver.session().run("Match(n) return count(n) as count", TransactionConfig.builder().build());
            System.out.println("Entity Count: " + result.single().values().get(0));
    }

Also, I have such sentences in logs: 

> No need to create transaction for [org.springframework.data.neo4j.repository.support.SimpleNeo4jRepository.toString]: This method is not transactional.

Code [here][1]

  [1]: https://github.com/shayantabrizi/sample-code-1

**Comment by shayantabrizi** [comment] 2021-05-30 14:53
I also tried moving the method to a separate Service class, but again no success.

**Comment by michael-simons** [comment] 2021-05-30 16:31
A couple of things:

- You are using the wrong `@Test` annotation import (You are using Junit4 but it must be 5 `org.junit.jupiter.api.Test`, otherwise the Spring extension won't work).
- The test is annotated with `@DataNeo4jTest`, all transactions will be rolled back afterwards. Observe this by running this test against a locally running instance.
- The test will fail because when you do the match with the pure driver the transaction won't be committed and the driver will use a different one. You can use the `Neo4jClient` or a transaction template. 

Here's one working example: 

```
@Test
	public void save_a_person(@Autowired Neo4jClient client) {
		repository.save(new Person("Ali", "Alavi", 20, new Member(new Club("Iran"), "2020")));

		Record personRecord = client.query("MATCH (n:Person) return n").fetchAs(Record.class).mappedBy((t, r) -> r)
			.one().get();
		Assertions.assertThat(personRecord.get("n").get("name").asString()).isEqualTo("Ali");
	}
```

Please notice that you must get the node ("n") and than the name.

Also notice when running against a stand alone instance, the record will disappear after the test as the tx will be rolled back.

The method in `StartUp` is indeed not running transactional as 

- `@Transactional` is proxy based
- `method` is called internally (that is inside the proxy) and the proxy will never see it
- About the `toString`: That seems due to the fact that you set the log level to trace

The only reason that your application says "entity count 4" is that 

- method is non transactional
- the driver itself is not using spring transactions (Have a look at the building blocks https://docs.spring.io/spring-data/neo4j/docs/6.1.1/reference/html/#building-blocks)


Now a working solution

Put everything into a service 

```java
package com.neo4j.sdn;

import java.util.Optional;
import java.util.Random;

import org.neo4j.driver.Driver;
import org.neo4j.driver.Result;
import org.neo4j.driver.TransactionConfig;
import org.springframework.data.neo4j.core.Neo4jTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class AService {

	private final Neo4jTemplate template;
	private final PersonRepository repository;
	private final Driver driver;

	public AService(Neo4jTemplate template, PersonRepository repository, Driver driver) {
		this.template = template;
		this.repository = repository;
		this.driver = driver;
	}

	@Transactional
	public void method() {
		template.deleteAll(Person.class);
		template.deleteAll(Club.class);
		// save by Neo4jTemplate
		Person person_1 = template.save(new Person("Reza", "Mahdavi", 22, new Member(new Club("Iran"), "2021")));
		// Save by Repository
		Person person_2 = repository.save(
			new Person("Ali" + new Random(System.currentTimeMillis()).nextInt(), "Alavi", 20,
				new Member(new Club("Iran"), "2020")));
		// Query by Repository
		Person ali = repository.findByName("Ali");
		// Query by Neo4jTemplate
		Optional<Person> reza = template.findById(person_1.getId(), Person.class);
		// Custom query
		Result result = driver.session().run("Match(n) return count(n) as count", TransactionConfig.builder().build());
		System.out.println("Entity Count: " + result.single().values().get(0));
	}
}
```

And use the service

```
package com.neo4j.sdn;

import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.stereotype.Component;

@Component
public class StartUp implements ApplicationListener<ContextRefreshedEvent> {
	private final AService aService;

	public StartUp(AService aService) {
		this.aService = aService;
	}

	@Override
	public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
		aService.method();

	}

}
```

You will notice that the service puts out "Entity Count: 0" but that is due to the fact that the transaction is working now and the driver uses a different one.

Please let me know if that helps.

**Comment by shayantabrizi** [comment] 2021-05-31 04:43
First of all let me thank you for all the time you put on this and all the useful hints you gave. Second, I tried your solution, but at first it didn't work. But after I changed the modifier of "method" from default (package-private) to public it worked. Is this a bug or is it expected to be so?

**Comment by michael-simons** [comment] 2021-05-31 06:14
I'm glad I could be of help!

No, this is not a bug ( definitely not on our side :) ), it's just the way `@Transactional` is implemented in Spring Core. It works via Proxy.

Those answers here
https://stackoverflow.com/a/4396530
https://dzone.com/articles/spring-transactional-and-private-methods-snippet

Should bring some more clarity. 

My recommendation is:
- Put every interaction with the database that involves more than one call to a repository / the template / the client into a dedicated service method into a dedicated service
- Make that method `@Transactional`
- Make sure that does methods are only called from outside the service. If you call a `@Transactional` method from a non `@Transactional` method in the same class, it will depend on the mode Spring Core is running in (can be JDK proxies, than it won't work or AspectJ proxies (than it will work)). I find this to brittle.


In the case of Neo4j: The `Driver` bean is _not_ participating inside those transaction. This is by design.

I'm glad that I could help you.

**Comment by michael-simons** [comment] 2021-06-01 13:58
If your issue is solved, can we close this?

**Comment by shayantabrizi** [comment] 2021-06-02 04:58
Sure. Thank you!

**Closed** 2021-06-07 08:42 UTC
Labels: status: feedback-provided
