### ISSUE TITLE
Same node with double Relationship not saved correctly

### ISSUE THREAD

**Issue by VladoKuruc** [spring-projects/spring-data-neo4j#2196] opened 2021-03-22 15:04 UTC
I have issue with saving node with multiple relationships (with diferent properties) with the same target node. Repository save() method only save last relationship.

To report this issue, I created this test case (test added to org.springframework.data.neo4j.integration.imperative.RepositoryIT.RelationshipProperties)
```java
	@Test
	void saveSameNodeWithDoubleRelationship(@Autowired HobbyWithRelationshipWithPropertiesRepository repository) {
		AltHobby hobby = new AltHobby();
		hobby.setName("Music");

		AltPerson altPerson = new AltPerson("Freddie");

		AltLikedByPersonRelationship rel1 = new AltLikedByPersonRelationship();
		rel1.setRating(5);
		rel1.setAltPerson(altPerson);

		AltLikedByPersonRelationship rel2 = new AltLikedByPersonRelationship();
		rel2.setRating(1);
		rel2.setAltPerson(altPerson);

		hobby.getLikedBy().add(rel1);
		hobby.getLikedBy().add(rel2);
		repository.save(hobby);

		hobby = repository.loadFromCustomQuery(altPerson.getId());
		assertThat(hobby.getName()).isEqualTo("Music");
		List<AltLikedByPersonRelationship> likedBy = hobby.getLikedBy();
		assertThat(likedBy).hasSize(2);

		assertThat(likedBy).containsExactlyInAnyOrder(rel1, rel2);
		}
```
I try it with SDN 6.0.x and master branch.

**Comment by meistermeier** [comment] 2021-03-22 16:45
Thanks for reporting it. I can reproduce it and thinking about how to solve the problem.
SDN wants to create both relationship code-wise but this is done in a `MERGE` statement. Since both relationships point towards the same entity, this is a little bit more tricky.
The underlying "blocker" is that we a very cautious when handling relationships with properties because we don't want to remove in the graph existing properties.

**Comment by meistermeier** [comment] 2021-03-24 08:25
Fixed with merge of GH-2198

**Closed by meistermeier** 2021-03-24 08:25 UTC
Labels: bug
