### ISSUE TITLE
Existing @RelationshipProperties are deleted when new relation is added

### ISSUE THREAD

**Issue by ma-ku** [spring-projects/spring-data-neo4j#2906] opened 2024-05-24 08:14 UTC
This is a followup to #2905 which probably did not make the point clear enough and this should try to give an example that allows to reproduce the behavior. 

The behavior is twofold: 

1. Saving multiple elements one after another creates duplicate relationships
2. Saving an element with a relationship with properties clears the properties of  other relationships with the same source node.

The test case can be found on my fork at https://github.com/ma-ku/spring-data-neo4j.

**Comment by ma-ku** [comment] 2024-05-24 08:25
Hit save by accident too early. Sorry

**Comment by ma-ku** [comment] 2024-05-28 07:13
I just want to add point your attention to the method `saveEntity` that basically resembles our core use-case where the data get's corrupted. The function will attach a new node to an existing node using a relationship with properties. When loading the target node it seems as if the reverse relation pointing from the target node to the source nodes is instantiated as a relation **without** properties and when saved, these new relationships basically replace the original relationships. I was trying to make sense of the logged statements but ultimately I could pinpoint the issue.

**Comment by meistermeier** [comment] 2024-05-28 08:13
Thanks for the input. I already jumped on this issue yesterday but don't have a conclusion yet.
As you have already noticed it is depending on which direction of the relationship gets saved/updated first. The relationship with properties is _only_ considered as such where it is defined. Modelling the opposite direction also as one _should_ solve the problem *but* I still have some issues. Still investigating what causes the probem.

**Comment by ma-ku** [comment] 2024-05-29 09:54
I am sure you had your reason when you the `@StartNode` and `@EndNode` logic but if you want to keep the relation navigable in both directions you might end up in a similar model?

**Comment by ma-ku** [comment] 2024-06-10 13:41
Any updates on that topic?

**Comment by michael-simons** [comment] 2024-06-11 08:03
I am still wondering what annotations `@StartNode` and `@EndNode` are, really…

**Comment by ma-ku** [comment] 2024-06-11 09:22
> I am still wondering what annotations `@StartNode` and `@EndNode` are, really…

I must say I am deeply disappointed by your communication manners. The last ticket #2905 was rejected with 'you are holding it wrong' and now I am bringing it up again with a complete test case that proves that there is an issue and the only thing is that I keep such an answer, again. I refer to https://docs.spring.io/spring-data/neo4j/docs/dev/api/org/springframework/data/neo4j/annotation/StartNode.html which was once part of the SDN API.

**Comment by michael-simons** [comment] 2024-06-11 09:29
Your comment is the most disrespectful I have read here in a long time, but I will answer nevertheless. Please be aware that here are humans at the other end as well, and we are only trying to support you on your use case

> *which was once part of the SDN API.*

I was not around when this was part of the API, hence I am asking. If I am not allowed to ask questions, we can close this right now.

And yes, in 2905 you did it hold wrong. We clearly showed that in the ticket.

This ticket we are analysing and it might be "it is not (yet) supported". 
We did not plan for bidirectional mapping of relationships with properties, but would add this if it is an important use case.

**Comment by ma-ku** [comment] 2024-06-11 09:46
My apologies for that, I did not know that you have not been around when this was part of the API. But honestly the responses on that ticket are pretty scarce and we are quite concerned that this is eventually an issue in the design that might hit us also in other places, as we for example also see massive deletions and recreations of relationships during save operations even though these have not been modified.

Please understand that the loss of bidirectionally is not acceptable in our model and at least from reading the documentation, there is no clear indication that bidirectionally is not supported with `@RelationshipProperties`. We found a workaround by adding an intermediate node that is only used to store the properties but that basically renders `@RelationshipProperties` useless unless you only use them in one direction. 

Regarding #2905. Your test cases did not cover one important aspect; the relationships are still there in the sense that the total number is correct, but the properties stored with the relation get dropped. So we experience a loss of information on entities we do not touch and that is what this ticket was about. So maybe holding it wrong is not entirely correct here but I liked the approach how that was handled as a test case and provided more insight with this ticket. I would have appreciated a bit more communication so I could have clarified this instead of just rejecting it.

**Comment by michael-simons** [comment] 2024-06-11 09:48
All good, Mathias, no hard feelings remain.
Wrt timely updates, see my comment here https://github.com/spring-projects/spring-data-neo4j/issues/2905#issuecomment-2129368975

> Your test cases did not cover one important aspect; the relationships are still there in the sense that the total number is correct, but the properties stored with the relation get dropped. So we experience a loss of information on entities we do not touch and that is what this ticket was about.

That I did miss. Thanks for clarifying.

**Comment by michael-simons** [comment] 2024-06-11 15:09
Hello @ma-ku 

Attached is a branch with
- the necessary changes on the *imperative* side atm for supporting bidirectional mapping of relationships with properties
- the necessary changes to your test code. As with Start/End node annotation (in there you would also had to have *two* relationship entities I guess, otherwise you can express the directions in a logical way), you need to variants of the relationship properties class. I took your class, introduced a generic type parameter, and following in that, two variants pointing in the reverse direction

Please take note that Neo4j the database itself *does not* have such a thing as bidirectional relationships. While you can match the following pattern `(n)-[:X]-(m)`, you can't create it (`create (n:A)-[:X]-(m:B) return *` leads to `Only directed relationships are supported in CREATE (line 1, column 13 (offset: 12))`).

Therefor we originally aimed to be true to product and actually do test that, see: https://github.com/spring-projects/spring-data-neo4j/blob/3ec8e504f0975ef844727535bbe1699f0f06a30d/src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java#L2479

I guess having two of the relationships in physical different direction *with* properties is not what you want.
Hence, the change, so that both the original behaviour stays intact *and* the one you most likely wish for.

Please test!

@meistermeier As promised, I would love to see you do the reactive bits on this.

Branch: https://github.com/spring-projects/spring-data-neo4j/tree/issue/2906

**Comment by ma-ku** [comment] 2024-06-12 07:55
Hi @michael-simons ,

thank you for the quick turnaround. I admit I still analyzing the changes. Technically you keep the notion of a one-way relation but you allow having two distinct instances represent the same 'physical' relation. I do of course understand that Neo4j does not have the bi-directionality in its representation but the modeling of relations in Java is of course different and allows traversal of a unidirectional edge in both ways, this is what I refer to as bidirectional. 

I am not sure if the split identity approach is the right way to go, I still need to check If our project can cope with that, at the moment I would say yes but I will let you know after testing is through. Just from a architectural standpoint, I at least would appreciate object identity in Java if we talk about the same thing (the relationship) but like I said before, this would be a different approach in the definition of the `@RelationshipObject.

One thing that we appreciate is that we can now have custom ids on the relationships that hopefully allow SDN to better determine which relationships need to be deleted or create in a save operation. We will also check that in our testing.

Will come back once we are through with testing.

**Comment by michael-simons** [comment] 2024-06-12 08:21
Thanks a lot already!
Looking forward to your results.

**Comment by ma-ku** [comment] 2024-06-12 10:18
Just a quick heads up on our progress; we have modeled the relationship class twofold like you did in the test case but we of course run into quite a few bumps in our code as the mapping between DTO and entities relied on a single type but that's at least for now just work but this is back to the idea of a single type with two properties for either direction.

Keep you updated.

**Comment by michael-simons** [comment] 2024-06-17 09:15
FYI we are working on the reactive parts.

**Comment by ma-ku** [comment] 2024-06-17 10:02
Hi, i was just about to write another comment. I have discussed the changes in the PR with the team and I will try to summarize the key points of this discussion:

We still don't think that the dual identity of the same thing is really a good solution; here are the arguments against this solution:
1. Updating the relationship via one of the existing instances may lead to inconsistent update behavior. While we can control which instance gets updated, there is no guarantee that SDN picks the right instance to create the new relationship (see the little snippet below that I created to verify this).
2. In order to help SDN identifying the in-memory relationships in the database, we could provide UUID for all relationships but since they are automatically also only traversable in one direction, this would impact or backend logic all across the place.

Besides this relationship issue there is another problem plaguing us which is partly related with this; the save times start increasing as every modification and addition on the nodes pulls in all related nodes that are connected via a relationship. As this is a known behavior, we will most likely be forced into using projections to limit the footprint of the save operations and thus keep the response times low. That being said, we will then most likely cut off these bidirectional relationships going out from the `BugTargetBase`. With that regard, this would reduce the immediate need for a working solution for the app to operate correctly but this change does of course not affect the general data model so the modeling of relationships with properties that are bidirectionally traversable (in Java) remains.

So the ask would still be to handle the bidirectionally with one class and one instance in memory. Eventually adding a `@OriginNode` annotation would help but I do not want to dictate any solutions, you are the masters of SDN.

Overall, this feels clumsy in the usage of the SDN and we would appreciate a more generic and versatile approach to cope with the complexities of the underlying graph. Don't get me wrong, projections by themselves are a very smart solution but it has it's limitations as basically every data access use-cases that is driven mainly from the frontend logic and the APIs is rippling into the backend and kind of hits the repositories and the related projection definitions which we consider a pretty significant impact through the various architectural layers of the backend, but that might be debatable.  Nevertheless, all these effects force developers into creating additional definitions which is of course tedious and repetitive work and I have good understanding for our developers that are even voting to completely abandon SDN and go only with direct data access, but at least we in the architecture team consider this a bit too radical.

Here is another thing you might be interested in but maybe I oversaw something; I tried to create a test that verifies how SDN would handle parallel updates to the same physical relationship if the two independent instances of it get updated at the same time. I pulled your latest changes and added these lines to the test cases `saveSingleEntitiesToLeaf` and `saveSingleEntitiesToContainer` and in both cases the tests already fail accessing the `reli` property of `from1Loaded`, so apparently there is still a glitch in the loading logic?
``` 
var from1Loaded = fromRepository.findById(from1.uuid).orElseThrow();
from1Loaded.reli.target.relatedBugs.forEach(bug -> bug.comment += " Change 1");
from1Loaded.reli.comment += " Change 2";	
fromRepository.save(from1Loaded);
```

**Comment by michael-simons** [comment] 2024-06-17 10:33
Thanks for the detailed comment, we will discuss the comment later this week.

Question upfront though: While a bidi mapping is helpful on stuff read from any database, I get this, you aren't going to get away with updating both sides of it in other solutions, either? I know for a fact that in Neo4j-OGM this is the case and I would assume in Hibernate ORM it's similar, isn't it? Aka, wouldn't it be similar error prone?

Only partially related btw, but as I do mention OGM above, you are aware that we fully support Neo4j-OGM with latest Spring Boot versions as well? https://github.com/neo4j/neo4j-ogm-spring
Many of the issues we are seeing ever since SDN-RX turned into SDN 6 and later, stem from the fact that we catered a lot for the reactive workflow, especially avoiding any local session state (hence more updates on write), working row (record) based, and not on a local sub-graph. Took us a while to realise that, as the early feedback on SDN-RX was ofc focussed on reactive, with people having a bit separate goals, but eventually, we decided to not ditch Neo4j-OGM. 
It might work better for you and will continue working with Neo4j 5 and later.

**Comment by michael-simons** [comment] 2024-06-19 09:38
Update: Working on the loading atm. If you would declare the 

```
@Relationship(type = "RELI", direction = Relationship.Direction.INCOMING)
	public BugRelationship2 reli;
```

in `BugFrom` as `IncomingBugRelationship`, it would work until it fails (cannot use immutable constructor with cycles, that has always been the case). 
The reason it does not fail as it should now is that Spring Framework itself struggles to detect the correct generic type. I'll see if I can work around that first.

**Comment by ma-ku** [comment] 2024-06-19 10:32
Will try this. Probably I need to better understand the process of loading and materializing nodes relationships. That the circle is an issue means that you will not 'patch' an instance once it has been instantiated, correct?

**Comment by ma-ku** [comment] 2024-06-19 11:19
And in addition; does that behavior mean that we can not have cyclic dependencies in the graph?

**Comment by michael-simons** [comment] 2024-06-20 13:47
Hej.

Ofc you can have cyclic dependencies in the graph. 

They are just - at least for us - painful in the OGM, especially when it comes to immutability, which was one requirement for us (i.e. be able to support proper Java records). So, we need to have relationship isomorphism similar to what Neo4j has (i.e. only traverse each relationship once while mapping (we could be better here in our algorithm)), plus the ability to observer which object is under construction.

Furthermore, sometimes cycles are hidden away in domain models via the use of nested base classes.

Anyhow, regardless of that, I pushed the reactive implementation last night and the working example of the domain outlined in the reproducer, including the added test from above.

Plan is to merge it next week.

Cheers, and thanks for your feedback and investigation again.

**Comment by meistermeier** [comment] 2024-08-01 07:20
The changes are merged. Closing this issue.
If there is anything coming up, please raise a new issue.
Thanks for the valuable input 🙇

**Closed by meistermeier** 2024-08-01 07:20 UTC
Labels: status: waiting-for-triage
