### ISSUE TITLE
Id must be assignable to Serializable error with 4.1.3

### ISSUE THREAD

**Issue by ssherwood** [spring-projects/spring-data-neo4j#366] opened 2016-10-05 13:03 UTC
Per previous conversation about this issue started here:  https://github.com/spring-projects/spring-boot/issues/6709

When upgrading to Spring Boot 1.4.1 our projects started generating errors:

```
{"cause":null,"message":"Id must be assignable to Serializable! Object of class [null] must be an instance of interface java.io.Serializable"}
```

Reverting back to Boot 1.4.0 reverted to expected behavior.  It appears this is some kind of regression introduced in 4.1.3 as that is the default version in 1.4.1.

A simple project with the error is here: https://github.com/ssherwood/demo-neo4j

**Comment by mangrish** [comment] 2016-10-06 03:20
Hi @ssherwood.

I will take a look soon. In the mean time can you try 4.2.0.BUILD-SNAPSHOT and see if your problem persists. You can see an example on how to use the snapshot with Spring Boot 1.4.1 here: https://github.com/neo4j-examples/sdn4-university/tree/4.2.x.

**Comment by ssherwood** [comment] 2016-10-06 13:32
@mangrish I'm trying to emulate your work but I'm getting a new error:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.example.DemoNeo4jApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/data/neo4j/config/Neo4jConfiguration.class] cannot be opened because it does not exist
```

I'm not sure what might be at issue (it might be my environment since I'm working behind a proxy and have to jump through hoops to get at SNAPSHOTS).  I'll commit my code to https://github.com/ssherwood/demo-neo4j and try from home to be sure.

**Comment by vince-bickers** [comment] 2016-10-19 08:52
@ssherwood  Did you manage to resolve this problem?

**Comment by ssherwood** [comment] 2016-10-21 09:00
@vince-bickers No.  I've tried a lot of things so far and have not had any succees unless I revert entirely back to Spring Boot 1.4.0.  I'm doing these builds at home now and am running inside IntelliJ with a clean repo, so I can rule out a lot of environmental causes.

For me, the Ingalls-BUILD-SNAPSHOT seems to be missing the Neo4jConfiguration class:

```
java.io.FileNotFoundException: class path resource [org/springframework/data/neo4j/config/Neo4jConfiguration.class] cannot be opened because it does not exist
```

I noticed that the sdn4-university provides its own Neo4jConfiguration class which seems to be defeating the purpose of using Spring Boot's autoconfig approach.  I suspect this is why your examples are not experiencing the same problem.

When I switch to Hopper-SR4, the config class returns and I can actually start up the application but the serialization error returns:

```
{"cause":null,"message":"Id must be assignable to Serializable! Object of class [null] must be an instance of interface java.io.Serializable"}
```

Interestingly, the nodes actually get created in Neo4j but I can view them with the Spring Data Rest interfaces.

**Comment by tigrou83** [comment] 2016-11-09 15:15
I have the same problem than ssherwood with spring boot 1.4.2.RELEASE and spring-data-neo4j 4.2.0-SNAPSHOT:

org.springframework.beans.factory.BeanDefinitionStoreException: **Failed to process import candidates for configuration class [com.nagra.ml.sp.cpm.core.CpmNeo4jConfiguration]**; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/data/neo4j/config/Neo4jConfiguration.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:541)
	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:475)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:324)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:270)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.nagra.ml.sp.cpm.core.Application.main(Application.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

**Caused by: java.io.FileNotFoundException: class path resource [org/springframework/data/neo4j/config/Neo4jConfiguration.class] cannot be opened because it does not exist**
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:172)
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:50)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:98)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:89)
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:76)
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:93)
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:633)
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:796)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:308)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.processMemberClasses(ConfigurationClassParser.java:329)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:247)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:230)
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:532)
	... 23 common frames omitted

**Comment by kbastani** [comment] 2016-11-11 10:47
This issue looks to be resolved after this commit from @luanne https://github.com/spring-projects/spring-data-neo4j/commit/3c26a646874e766d9f8ac87dc30c07f682969edb

I ran into the same issue. The cause was due to a bug when checking whether or not an ID field was either an enum or a simple type. The bug was introduced with this commit: https://github.com/spring-projects/spring-data-neo4j/commit/37179a3a2cc1a94d1963b8da453bdbfdbba3cecf. This was diagnosed by @xenoterracide in this comment: https://github.com/spring-projects/spring-boot/issues/6709#issuecomment-251554644

There is an issue at the moment when trying to use the `4.2.0.BUILD-SNAPSHOT` with any Spring Boot release <= `1.4.3`. The Spring Boot auto-configuration project is dependent on scanning for the `Neo4jConfiguration` class when `spring-data-neo4j` is found on the classpath of the application. Since the `Neo4jConfiguration` class was removed in the latest `4.2.0.BUILD-SNAPSHOT`, the class loader for Spring Boot will not be able to find the `Neo4jConfiguration` file at the expected location `org/springframework/data/neo4j/config/Neo4jConfiguration.java`.

This bug will need to be fixed in the Spring Boot auto-configuration project. 

https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.java#L36

Since I do not have the history on why `Neo4jConfiguration` was removed, I think it's best that @luanne or @mangrish raise this issue against https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/neo4j/Neo4jDataAutoConfiguration.java#L36

Spring Data Neo4j will continue to be broken for applications using Spring Data REST repositories until this is resolved. There is no workaround in the meantime.

/cc @philwebb @snicoll

**Comment by mangrish** [comment] 2017-01-12 03:36
Moved to: https://jira.spring.io/browse/DATAGRAPH-955

**Closed by mangrish** 2017-01-12 03:36 UTC
Labels: needs investigation
