### ISSUE TITLE
Relationship not working with SDN 6.x

### ISSUE THREAD

**Issue by paolodedo** [spring-projects/spring-data-neo4j#2129] opened 2021-01-26 15:21 UTC
Hello,

🔵Spring Boot 2.4.1

🔵Spring Data Neo4j 6.0.2

I am noticing that Relationships are not working on the new SDN version (with Spring Boot 2.x and SDN 5.x).

My node models:

```
@Node
@Getter
@Setter
public class Device {

    @Id
    @GeneratedValue
    private Long node_id;

    private Long deviceId;

    private String name;

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "groupId")
    @JsonIdentityReference(alwaysAsId = true)
    @Relationship(type = "IS_LINKED", direction = Relationship.Direction.INCOMING)
    private Set<Group> groups = new LinkedHashSet<>();

    @Override
    public String toString() {
        return "Device{" +
                "node_id=" + node_id +
                ", deviceId=" + deviceId +
                ", name='" + name + '\'' +
                '}';
    }
}
```

```
@Node
@Getter
@Setter
public class Group {

    @Id
    @GeneratedValue
    private Long node_id;

    private Long groupId;

    private String name;

    private String[] tags;

    private String description;

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "deviceId")
    @JsonIdentityReference(alwaysAsId = true)
    @Relationship(type = "IS_LINKED")
    private Set<Device> devices = new LinkedHashSet<>();

    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "groupId")
    @JsonIdentityReference(alwaysAsId = true)
    @Relationship(type = "GROUP_LINK")
    private Set<Group> groups = new LinkedHashSet<>();

    @Override
    public String toString() {
        return "Group{" +
                "node_id=" + node_id +
                ", groupId=" + groupId +
                ", name='" + name + '\'' +
                ", groupType=" + Arrays.toString(tags) +
                ", description='" + description + '\'' +
                '}';
    }
}
```

🔴Every time **I try to add a Device into a Group, and save through GroupRepository** (which `extends PagingAndSortingRepository<Group, Long>`), no relationship is persisted onto Neo4j.

🔴Every time **I try to invoke a query** like `match (group1:Group {groupId: $groupId})-[:IS_LINKED]->(device:Device) return device limit $limit` **from Neo4j's dashboard**, it works well, **if I use it on a Repository with `@Query`, it does not work at all**, returning this exception: `NoRootNodeMappingException: Could not find mappable nodes or relationships inside Record<{device: node<13>}>
`

Thanks for your kind help,

Paolo

**Comment by meistermeier** [comment] 2021-01-26 15:49
Thanks for reporting this. We will look into the persist operation problem.
For the custom loading part: The Neo4j browser does graphically a little bit more than your query expresses. You could see the real results e.g. in the table view.
The problem with your query is that you neither return the group nor the relationship in the return part of the query. Assuming that you are still working with the `GroupRepository` the query should be `match (group1:Group {groupId: $groupId})-[r:IS_LINKED]->(device:Device) return group1, collect(r), collect(device) limit $limit`

**Comment by paolodedo** [comment] 2021-01-26 16:12
Ok thanks for the query, it works well.

I wait for the persist operation, so.

Thank you!!! 🥇

**Comment by michael-simons** [comment] 2021-01-26 16:25
Is there a reason you want to do this with a custom query?

**Comment by paolodedo** [comment] 2021-01-26 16:31
It is an implementation that always works, since model mappings are not, atm.

**Comment by michael-simons** [comment] 2021-01-26 16:34
I am not sure if I get this. I mean, we do generate pretty much that query for a `findAll` or similar on that repo. 

I'm not criticizing the use of custom queries at all, I am just wondering.

**Comment by paolodedo** [comment] 2021-01-26 16:43
Again, when mappings will consistently work, I'll switch

**Comment by paolodedo** [comment] 2021-01-27 14:27
@michael-simons 
I have managed to create relationships with Cypher now, gaining the mapped-relationships mechanism working again.
I am now using .getDevices() instead of a dedicated custom Cypher query.

The only remaining doubt is about `org.springframework.data.neo4j.core.mapping.NoRootNodeMappingException: Could not find mappable nodes or relationships inside Record<{device: node<16>}> for org.springframework.data.neo4j.core.mapping.DefaultNeo4jPersistentEntity@d180961
`

for this very query
`    @Query("match m1=(group1:Group {groupId: $groupId})-[:GROUP_LINK*]->(groupN:Group)-[:IS_LINKED *]->(device:Device) return device ORDER BY length(m1) limit $limit")
`

What about it? On neo4j dashboard, the result it gives me makes me sure of its successful mapping..
Am I doing something wrong?

Thanks :)

**Comment by myfrontpocket** [comment] 2021-03-10 14:09
I've faced a similar issue with a setup similar to the OP.  I _think_ the issue here is the relationship `IS_LINKED` for `Device` is on `Device` as an incoming relationship, and also exists on `Group` (as an outgoing).  In this scenario, to get the relationship to persist, I have to save both nodes.  For example, with your code, in a very basic way:

```
Device device = new Device();
Group group = new Group();
group.setDevices(Set.of(device));
groupRepository.save(group);
device.setGroups(Set.of(group));
deviceRepository.save(device);
```

**Comment by aslak-dirdal** [comment] 2021-03-10 14:55
I'm having the same issue, but I dont have relation linked from both sides.

This works adding the relationship:
```
val user = userRepository.findById(userId)
val document = Document(id = randomId)
document.concerns = Concerns(user)
documentRepository.save(document)
```

But this does not remove the relationship:
```
val document = documentRepository.findById(documentId)
document.concerns = null
documentRepository.save(document)
```

**Comment by meistermeier** [comment] 2021-03-10 17:05
Could you please checkout (either physically or mentally) https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2129 ?
I created tests and setup for every example mentioned in here. Maybe I have misinterpreted your use-cases.
My project uses the latest released version (currently 6.0.5) of SDN that comes with the latest stable Spring Boot 2.4 release.

**Comment by aslak-dirdal** [comment] 2021-03-10 17:16
I will check. I'm also using Spring Boot 2.4.3 with SDN 6.0.5

I have also created a simple test repo with my issue:
https://github.com/humawork/stackoverflow-66564591

**Comment by myfrontpocket** [comment] 2021-03-10 17:22
I can't actually get these tests to run. I get the error: `org.neo4j.driver.exceptions.ClientException: The client has provided incorrect authentication details too many times in a row.`

But just glancing at it, the tests seem accurate.  In the `saveUnidirectional` test, if you comment/remove either line 35 for 37, it should fail.

**Comment by myfrontpocket** [comment] 2021-03-10 17:33
Okay let me try this comment again... juggling different things...

I can't actually run these tests because I get an authentication error.  Looking for them, they seem to be accurate.  Are `saveUnidirectional` and `saveBidirectional` passing?

**Comment by meistermeier** [comment] 2021-03-10 18:39
1. @aslak-dirdal Provided ids without any generator will always make the entity appear as new. There is also a warning when you persist this.
```
2021-03-10 19:28:09.665  WARN 435746 --- [           main] o.s.d.n.c.m.DefaultNeo4jIsNewStrategy    : Instances of class com.example.demo.Document with an assigned id will always be treated as new without version property!
```

2. @myfrontpocket I introduced testcontainers, so you could basically now to a simple `./mvnw clean verify` and the container will spawn and the tests will run without the need of having a running db instance. And yes, the purpose of my example project is to have all tests passing ;)
What I assume is that you may have a `@Transactional` boundary around the tests in your setup and you are verifying this with something that does not participate in the (Spring) transaction, like the Neo4j driver (as in my example).
The `Neo4jClient`, as a part of SDN and Spring transaction aware, can verify the results within the same transaction. I added an example to the `saveUnidirectional` test on how this would look like.

**Comment by aslak-dirdal** [comment] 2021-03-10 19:01
Well. Most nodes in my database have one or more relationships so maybe just add: version = 0 to all nodes before upgrading to Spring Boot 2.4

**Comment by myfrontpocket** [comment] 2021-03-10 19:14
> 1. @aslak-dirdal Provided ids without any generator will always make the entity appear as new. There is also a warning when you persist this.
> 
> ```
> 2021-03-10 ....DefaultNeo4jIsNewStrategy    : Instances of class com.example.demo.Document with an assigned id will always be treated as new without version property!
> ```
> 
> (Edit: missing paragraph added)
> If an entity is new, SDN will not remove existing relationships because it does not know that there are any.
> 
> 1. @myfrontpocket I introduced testcontainers, so you could basically now to a simple `./mvnw clean verify` and the container will spawn and the tests will run without the need of having a running db instance. And yes, the purpose of my example project is to have all tests passing ;)
>    What I assume is that you may have a `@Transactional` boundary around the tests in your setup and you are verifying this with something that does not participate in the (Spring) transaction, like the Neo4j driver (as in my example).
>    The `Neo4jClient`, as a part of SDN and Spring transaction aware, can verify the results within the same transaction. I added an example to the `saveUnidirectional` test on how this would look like.

Thanks @meistermeier.  I reran your tests and they all pass.  For my/our own usage, the repository tests do not use `@Transactional`.  We use a test DB to CRUD data for tests, and all data is removed in an `@AfterEach`.

**Comment by myfrontpocket** [comment] 2021-03-10 20:18
@meistermeier Any tips or suggestions would be appreciated.

**Comment by myfrontpocket** [comment] 2021-03-11 00:00
@meistermeier Doing a bit more playing around with my tests, I've figured out that the equivalent of `Group` (the domain with the relationship as outgoing) in my code is abstract.  When I do this, remove the equivalent  `device::setGroups` and `deviceRepository::save`, and then run the test, I can see in the DB once the test finishes that the relationship is persisted.  Once I add `abstract` back and rerun the test, I can see in the DB once it finishes that the relationship is missing.  I hope this helps!

**Comment by myfrontpocket** [comment] 2021-03-11 01:43
Unfortunately, using the `neo4j-issues` code, I can't get this to replicate as I've described.  Not sure what's missing.

**Comment by meistermeier** [comment] 2021-03-11 07:42
@aslak-dirdal using a generator (e.g. the UUID generator) is a valid option and won't require the version (optimistic locking).

@myfrontpocket For completeness, could you by any chance share a minimal project that reproduces this problem?

**Comment by aslak-dirdal** [comment] 2021-03-11 08:46
@meistermeier Thanks for you help. I tried that, and it kind of worked, but now I got several other issue. I will have to postpone the upgrade as this is to time consuming at this point. I might create a new issue later with a reproducable example. Do you prefer a pull request to your repo, or do you want me to share a repo?

**Comment by meistermeier** [comment] 2021-03-11 09:28
It's really up to you. If you just want to provide a reproducer, it might be better to just share the project.

@myfrontpocket I do not why I haven' t seen your additional comments. Maybe you are using an older version of SDN / Spring Boot in your project?

**Comment by myfrontpocket** [comment] 2021-03-11 14:24
@meistermeier Nope, I'm on Spring Boot 2.4.3.  I've been playing around with my test again this morning, and I've managed to get it down to one save.  I still have to manage both sides though.  Here's the equivalent OP code:

```
Device device = new Device();
Group group = new Group();

group.setDevices(Set.of(device));
device.setGroups(Set.of(group));

groupRepository.save(group);

var consumed = groupRepository.findById(group.getNode_id()).get();

assertThat(consumed.getDevices()).isNotEmpty();
```

This kind of test will pass for me.  If I comment out `device.setGroups(Set.of(group));`, then the test fails.

**Comment by Sm0keySa1m0n** [comment] 2021-05-02 08:09
I'm experiencing this issue too.

**Comment by Sm0keySa1m0n** [comment] 2021-05-03 10:49
I've discovered that relationships don't save if you set the value of the relationship using a setter however, if you set the value of the relationship in the constructor it persists correctly. For example 
```java
repo.save(new User(new Friend()))
```
will work but
```java
User user = new User();
user.setFriend(new Friend());
repo.save(user);
```
will not persist the friend and in turn will not persist the relationship.

**Comment by meistermeier** [comment] 2021-05-03 15:47
Could you provide any more information @Sm0keySa1m0n ? 
Would be really helpful to see your domain, or even better a complete reproducer if you have it at hand.

**Comment by Sm0keySa1m0n** [comment] 2021-05-03 19:23
I just created a simple project using start.spring.io which contained Spring Data Neo4j (with Spring Boot 2.4.5 and Java 15). I then created two classes with a property annotated with `Relationship`, one object had an incoming property, the other an outgoing. Then I created a new object using one of the classes I created and set the annotated relationship field to new instance of the other class and saved the object using a `ReactiveNeo4jRepository`. The object which is stored in the relationship field is not persisted and thus neither is the relationship. I've tried this either way round, using generated IDs, optimistic locking and saving both objects separately before setting the relationship fields none of which work.

**Comment by meistermeier** [comment] 2021-05-04 05:53
How does the entity classes look like? There must be something different beyond the obvious.
Are the properties on the class immutable?

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 07:00
The ID is immutable and that's it.

**Comment by meistermeier** [comment] 2021-05-04 07:07
"Great" (for the right interpretation of great)
This is something explainable then. Before I ask now again for another information, I just assume that your class looks like
```
class User {

private final Long id;
private List<Friend> friends;

public User(Long id) {
  this.id = id;
}

// setter for friends etc.
}
```
right?
What happens, and this is completely out of SDN's scope but a general Spring Data behaviour, is:
Because the `id` field is immutable and the only chance for Spring Data to set the `id` is to call the constructor, a new instance of `User` will get created. The constructor itself does not respect the additional property `friends`. As a result, the object will on further process not have any relationship to persist because it is not set.

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 08:53
Yeah that's right. I tried using a wither statement and also tried adding a version field but to no avail.

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 08:56
I've also tried adding friends as a parameter to the constructor.

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 10:44
That would make sense as to why it works when you pass friends into the constructor.

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 11:30
I've now removed all final fields and the constructor but relationships are still not being persisted.

**Comment by Sm0keySa1m0n** [comment] 2021-05-04 12:11
Never mind, it works with Spring Boot 2.4.5 but not with Spring Boot 2.5.0-SNAPSHOT.

**Comment by meistermeier** [comment] 2021-05-05 09:19
The snapshot release is a moving target but right now it has SDN 6.1.0 as a dependency and the mutable approach works, also see https://github.com/meistermeier/neo4j-issues-examples/tree/master/spring-boot-next for the naive example.
Also there is a branch https://github.com/meistermeier/neo4j-issues-examples/tree/gh-2129_immutable/spring-boot-next for a complete immutable `User`.

**Comment by Sm0keySa1m0n** [comment] 2021-05-06 19:26
I've discovered that the problem was occurring when I use a custom ID type. I'm trying to use a BSON Object ID but when I do so, relationships don't persist.

**Comment by Sm0keySa1m0n** [comment] 2021-05-06 19:38
In fact, it seems it will only work with Longs, I've even tried strings but they don't work.

**Comment by Sm0keySa1m0n** [comment] 2021-05-08 13:40
New update: Relationships wont persist when you have a custom ID AND a version property. Without a version property or without a custom ID, everything persists fine.

**Comment by Sm0keySa1m0n** [comment] 2021-05-11 16:21
I've done some more testing and it turns out that using an immutable ID was never an issue in the first place.

The underlying issue is the fact that if you use an ID with a type other than a long, relationships won't persists.

**Comment by Sm0keySa1m0n** [comment] 2021-05-14 16:11
Issue also only occurs if using optimistic locking

**Comment by michael-simons** [comment] 2021-07-15 12:54
Hi. As there has been no longer any activity, I'm gonna close this.

If there's a reproducer for

> The underlying issue is the fact that if you use an ID with a type other than a long, relationships won't persists.

I'm happy to open a new issue.
Thank you.

**Closed by michael-simons** 2021-07-15 12:54 UTC
Labels: blocked: awaiting feedback
