### ISSUE TITLE
Receive null relations in class that inherit abstract base class 

### ISSUE THREAD

**Issue by rullyalves** [spring-projects/spring-data-neo4j#2516] opened 2022-03-31 12:24 UTC
I have code similar to this:

```java

@Node("WalletTransaction")
abstract class WalletTransaction(
    @Id
    var id: String?,
    var value: BigDecimal?,

    @Relationship(type = "HAS")
    var walletTransactionStatus: List<TransactionStatusUpdate>?,

    @Relationship(type = "CHANGES")
    var balance: WalletBalance?,

    var createdAt: Long? = Instant.now().toEpochMilli(),
    var updatedAt: Long?,
) {
    val currentStatus get() = walletTransactionStatus?.lastOrNull()
}

@Node("Deposit")
class DepositTransaction(
    id: String? = null,
    value: BigDecimal? = null,
    walletTransactionStatus: List<TransactionStatusUpdate>? = null,
    balance: WalletBalance? = null,
    createdAt: Long? = Instant.now().toEpochMilli(),
    updatedAt: Long? = null,

    @Relationship("FROM")
    val from: Wallet? = null,

    @Relationship("TO")
    val to: Wallet? = null,
) : WalletTransaction(id, value, walletTransactionStatus, balance, createdAt, updatedAt)

```
when i try to retrieve all transactions, balance and walletTransactionStatus fields are always null, I would like to know if I'm making a mistake or if this is a possible bug.

**Comment by meistermeier** [comment] 2022-04-01 07:26
Could you please bring this into a reproducible example or at least add the missing bit of information?
What is missing here for me: An implementation of `WalletTransaction` and the code that loads the `DepositTransaction`.

**Comment by rullyalves** [comment] 2022-04-02 19:59
Currently what happens is:
if I create an instance of DepositTransaction and save the fields that are relations, ex:
balance /
walletTransactionStatus

when retrieving via polymorphic query, ex:

// Neo4jRepository
walletTransactionRepository.findAll();

all transactions are loaded, but abstract class relations are not

is similar to this: https://github.com/spring-projects/spring-data-neo4j/issues/2028

**Comment by meistermeier** [comment] 2022-04-21 10:14
I created https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2516 from the input you gave me. This is working. Maybe you can add your thoughts and differences, I might have overseen.

**Comment by meistermeier** [comment] 2022-04-22 06:04
There is now a https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2516-kt and it shows the same behaviour as the Java version.

**Comment by spring-projects-issues** [comment] 2022-04-29 06:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-05-06 06:05
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-05-06 06:05 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
