### ISSUE TITLE
Instantiation Error for an abstract type when trying to map an inner static class

### ISSUE THREAD

**Issue by myfrontpocket** [spring-projects/spring-data-neo4j#2176] opened 2021-03-11 19:07 UTC
Spring Boot 2.4.3.

I have an abstract class that has several inner static classes that extend it.  For example:
```
@Getter
@Setter
@Node
public abstract class OuterDomain {

  @Id
  @GeneratedValue
  private Long Id;

  // base properties and relationships

  @Getter
  @Setter
  @Node
  public static class InnerDomain extends OuterDomain {
    // constructors
  }
}
```

With repository:
```
@Repository
public interface OuterDomainRepository extends Neo4jRepository<OuterDomain, Long> {
  // some custom queries
}
```

In a repository test, if I create an object of `InnerDomain` and save it, and call a custom query for said object, the object is returned and my test will pass.  However, I've found that if I try to use a pre-existing `InnerDomain` object (created beforehand outside of the test), the test will error out with an instantiation error for `OuterDomain`.

To get around this, I had to create a "dummy" repository for the inner static class:
```
@Repository
public interface InnerDomainRepository extends Neo4jRepository<OuterDomain.InnerDomain, Long> {
}
```

Is this expected behavior?

**Comment by mp911de** [comment] 2021-03-11 19:50
> if I try to use a pre-existing InnerDomain object (created beforehand outside of the test)

Do you refer to having that object being stored in the database/repository prior to running your test?

**Comment by myfrontpocket** [comment] 2021-03-11 19:56
> > if I try to use a pre-existing InnerDomain object (created beforehand outside of the test)
> 
> Do you refer to having that object being stored in the database/repository prior to running your test?

Yes, it's in the database prior to the test.

**Comment by meistermeier** [comment] 2021-05-05 10:37
It should already work.
Please note that you have to add the correct labels in prior existing data:
```
try (Session session = driver.session()) {
	session.run("CREATE (:InnerDomain:OuterDomain)").consume();
}

List<OuterDomain> domains = repository.findAll();
assertThat(domains).hasSize(1);
assertThat(domains.get(0)).isOfAnyClassIn(OuterDomain.InnerDomain.class);
```
It could, however, work with a more current version of SDN because we removed the strictness if there is only one eligible concrete class (`InnerDomain`) an abstract class (`OuterDomain`) can be instantiated from.

**Comment by jposthauer** [comment] 2021-05-13 16:29
Hello @meistermeier, I am working with @myfrontpocket on the same project and we are still having this issue.

Spring Boot: 2.4.5
Spring Data Neo4j: 6.0.8

So far we are only able to resolve the instantiation error by creating the empty dummy repository for the inner static class.

**Comment by meistermeier** [comment] 2021-05-13 18:28
Could you have a look at https://github.com/meistermeier/neo4j-issues-examples/tree/master/gh-2176 and tell me where the differences are to your use-case?

**Comment by myfrontpocket** [comment] 2021-05-13 18:34
In our code base, the only difference I see, is that we're using `Neo4jRepository<OuterDomain, String>` with the our ID property annotated with: `@Id`, `@GeneratedValue(strategy = SomeStrategy.class)`

**Comment by myfrontpocket** [comment] 2021-05-13 18:42
Also, and I'm not sure if this makes a difference or not, you're using a hard statement to create the node for the test.  We instantiate new objects and save them using the respective repository.

**Comment by myfrontpocket** [comment] 2021-05-13 18:43
This issue doesn't present itself within our existing tests.  It's our existing data that breaks it.

**Comment by meistermeier** [comment] 2021-05-13 18:47
That should not make any difference. Regarding the ids: I just took what was written in the first message.
Could you tell me the full qualified name of the `@GeneratedValue(strategy = SomeStrategy.class)` ? 
The `@GeneratedValue` of SDN does not have a `strategy` but a `generatorClass` property.
Just as a repetition: You are sure that both labels are on the real data nodes?

**Comment by myfrontpocket** [comment] 2021-05-13 18:51
That was my mistake... old code...
```
@Id
@Property(name = "id")
@GeneratedValue(value = SomeStrategy.class)
```

Yes, our data is correct.  This example is based off our existing domain structure.  There is a third label (`OuterDomain` extends another domain), but I'm not sure if that is relevant.

**Comment by jposthauer** [comment] 2021-05-13 18:57
All our entity classes extend a base entity class and that is where the ID generation lives:

```
public abstract class BaseEntity<T extends GraphEntity<T>> {

  @Id
  @Property(name = "id")
  @GeneratedValue(strategy = SomeStrategy.class)
  protected String id;
```

```
@Node
public abstract class OuterDomain extends BaseEntity<OuterDomain> {
```

**Comment by myfrontpocket** [comment] 2021-05-13 19:08
Thanks @jposthauer .  I should have stated this from the start.

**Comment by meistermeier** [comment] 2021-05-14 13:00
I updated my example to reflect the latest information you gave me. Attention: The test will no prior execution drop all the data from the database.
It seems to be still working. I think it would be more helpful if you could provide the exception.

**Comment by jposthauer** [comment] 2021-05-14 16:29
Below is the stacktrace, User is the OuterDomain class:
```
java.lang.InstantiationError: com.logicgate.core.access.user.domain.User
	at com.logicgate.core.access.user.domain.User_Instantiator_c8lslv.newInstance(Unknown Source)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator$EntityInstantiatorAdapter.createInstance(ClassGeneratingEntityInstantiator.java:238)
	at org.springframework.data.mapping.model.ClassGeneratingEntityInstantiator.createInstance(ClassGeneratingEntityInstantiator.java:87)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.instantiate(DefaultNeo4jEntityConverter.java:373)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.lambda$map$4(DefaultNeo4jEntityConverter.java:258)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.map(DefaultNeo4jEntityConverter.java:289)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:106)
	at org.springframework.data.neo4j.core.mapping.DefaultNeo4jEntityConverter.read(DefaultNeo4jEntityConverter.java:65)
	at org.springframework.data.neo4j.core.mapping.Schema.lambda$getRequiredMappingFunctionFor$0(Schema.java:96)
	at org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:234)
	at org.springframework.data.neo4j.core.PreparedQuery$AggregatingMappingFunction.apply(PreparedQuery.java:154)
	at org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:45)
	at org.springframework.data.neo4j.core.DelegatingMappingFunctionWithNullCheck.apply(DelegatingMappingFunctionWithNullCheck.java:35)
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:284)
	at java.base/java.util.Optional.flatMap(Optional.java:294)
	at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:661)
	at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:53)
	at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:85)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy193.findByEmailWithAudit(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.logicgate.core.common.support.LoggingAspect.profileAllMethods(LoggingAspect.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy193.findByEmailWithAudit(Unknown Source)
	at com.logicgate.core.access.user.service.AdminUserService.createAdmin(AdminUserService.java:55)
	at com.logicgate.core.access.user.service.AdminUserService$$FastClassBySpringCGLIB$$168d400a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at com.logicgate.core.common.support.LoggingAspect.profileAllMethods(LoggingAspect.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.logicgate.core.access.user.service.AdminUserService$$EnhancerBySpringCGLIB$$607cf448.createAdmin(<generated>)
	at com.logicgate.core.config.bootstrap.SecurityBootstrap.bootstrap(SecurityBootstrap.java:52)
	at com.logicgate.core.config.bootstrap.SecurityBootstrap.onApplicationEvent(SecurityBootstrap.java:44)
	at com.logicgate.core.config.bootstrap.SecurityBootstrap.onApplicationEvent(SecurityBootstrap.java:18)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at com.logicgate.core.ApiApplication.main(ApiApplication.java:20)
```

**Comment by meistermeier** [comment] 2021-05-27 07:58
The exception states clear that it tries to use the `OuterDomain` instead the inner one. But I am wondering if you have checked my example and maybe could add one or two changes to it to make it behave as in your code?
I cannot see any way to break my example in a way to produce this instantiation error.

**Comment by myfrontpocket** [comment] 2021-06-02 14:31
@meistermeier Can you double check your test?

In the test, you've created ONE object, but you're asserting that you've have TWO after a `findAll`.

![image](https://user-images.githubusercontent.com/30394985/120498970-aa4e5f00-c38d-11eb-8ed2-135fb1a0ca8d.png)

**Comment by jposthauer** [comment] 2021-06-02 19:04
@meistermeier I was able to replicate the issue with a few modifications to your test application: [Here](https://github.com/jposthauer/neo4j-issues-examples)

**Comment by jposthauer** [comment] 2021-06-03 17:51
It seems that there are actually two different issues giving the same error. The one I replicated above is the issue I was seeing but the issue @myfrontpocket is referring too is slightly different. I am currently trying to replicate that issue with your example and will report back if I am successful.

**Comment by meistermeier** [comment] 2021-06-04 04:45
Thanks for the effort already. But just to be in sync. With your posted example (master branch) I get a `MappingException` with `The schema already contains a node description under the primary label Field`.
Adding a explicit label (like `@Node("InfiniteField")`) to the `InfiniteField` (as a workaround) fixes the test for me.

**Comment by meistermeier** [comment] 2021-06-22 07:25
Any news here, otherwise I would like to close this issue for now?

**Comment by myfrontpocket** [comment] 2021-06-22 11:32
I recently retested with the latest release for the problem I reported, and I'm still seeing it. For now, we have dummy repositories to workaround this issue. I'm not aware if @jposthauer was able to reproduce it.

**Comment by jposthauer** [comment] 2021-06-22 14:42
We are still unable to reproduce this issue in a simple app but the workaround is good enough for us for now. We plan on circling back to this issue once we have other issues resolved.

**Comment by meistermeier** [comment] 2021-06-23 17:22
So I will close this for now here because as I said, the label is mandatory because of the hierarchy you are working with.

**Closed by meistermeier** 2021-06-23 17:22 UTC
Labels: blocked: awaiting feedback
