### ISSUE TITLE
ReactiveNeo4jRepository/ReactiveNeo4jTemplate - saveAll method implementation [DATAGRAPH-1339]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-neo4j#1902] opened 2020-07-27 15:33 UTC
**[Gerrit Meier](https://jira.spring.io/secure/ViewProfile.jspa?name=gerrit.meier)** opened **[DATAGRAPH-1339](https://jira.spring.io/browse/DATAGRAPH-1339?redirect=false)** and commented

Description
Method org.neo4j.springframework.data.core.ReactiveNeo4jTemplate#saveAll does not save `@DynamicLabels`

Stack:

Java 11
Spring boot version: 2.3.0.RELEASE
SDN/RX version: 1.1.1
Neo4j version: 4.0 and 4.1
How to reproduce?
Our simplified steps to reproduce

Create entity

```java
@Node("Column")
public class DaeColumnNode {
    @Id
    private String daeId;

    @DynamicLabels
    private Set<String> labels = new HashSet<>();

    public String getDaeId() {
        return daeId;
    }
    public DaeColumnNode setDaeId(String daeId) {
        this.daeId = daeId;
        return this;
    }

    public Set<String> getLabels() {
        return labels;
    }
    public DaeColumnNode setLabels(Set<String> labels) {
        this.labels = labels;
        return this;
    }
}
```

Create and run test

```java
@Testcontainers
@ReactiveDataNeo4jTest
class ReactiveColumnNodeTest {

	@Container
	private static Neo4jContainer<?> neo4jContainer = new Neo4jContainer<>("neo4j:4.1");

	@DynamicPropertySource
	static void neo4jProperties(DynamicPropertyRegistry registry) {
		registry.add("org.neo4j.driver.uri", neo4jContainer::getBoltUrl);
		registry.add("org.neo4j.driver.authentication.username", () -> "neo4j");
		registry.add("org.neo4j.driver.authentication.password", neo4jContainer::getAdminPassword);
	}

	@Test
	void shouldSaveAndReadEntities(@Autowired ReactiveNeo4jTemplate neo4jTemplate) {
		DaeColumnNode column = new DaeColumnNode();
		column.setDaeId("123-abc");
		column.setLabels(new HashSet<>(){{
			add("Column");
			add("Model");
			add("Data");
		}});


		StepVerifier.create(neo4jTemplate.save(column))
			.expectNextCount(1L)
			.verifyComplete();

		StepVerifier.create(neo4jTemplate.findAll(DaeColumnNode.class))
			.consumeNextWith(response -> {
				assertThat(column.getDaeId().equals(response.getDaeId()));
				assertThat(response.getLabels().contains("Model"));
				assertThat(response.getLabels().contains("Data"));
			})
			.verifyComplete();
	}


	@Test
	void shouldSaveAllAndReadAllEntities(@Autowired ReactiveNeo4jTemplate neo4jTemplate) {
		DaeColumnNode column = new DaeColumnNode();
		column.setDaeId("987-zyx");
		column.setLabels(new HashSet<>(){{
			add("Column");
			add("Model");
			add("Data");
		}});


		StepVerifier.create(neo4jTemplate.saveAll(Collections.singletonList(column)))
			.expectNextCount(1L)
			.verifyComplete();

		StepVerifier.create(neo4jTemplate.findAll(DaeColumnNode.class))
			.consumeNextWith(response -> {
				assertThat(column.getDaeId().equals(response.getDaeId()));
				assertThat(response.getLabels().contains("Model"));
				assertThat(response.getLabels().contains("Data"));
			})
			.verifyComplete();
	}
}
```

Test "shouldSaveAndReadEntities" (save method is used) will pass
Test "shouldSaveAllAndReadAllEntities" (saveAll method is used) will fail beause response.getLabels() is empty collection

How to reproduce? (with controller)
Our steps to reproduce

Create entity

```java
@Node("Column")
public class DaeColumnNode {
    @Id
    private String daeId;

    @DynamicLabels
    private Set<String> labels = new HashSet<>();

    public String getDaeId() {
        return daeId;
    }
    public DaeColumnNode setDaeId(String daeId) {
        this.daeId = daeId;
        return this;
    }

    public Set<String> getLabels() {
        return labels;
    }
    public DaeColumnNode setLabels(Set<String> labels) {
        this.labels = labels;
        return this;
    }
}
```

Create repository

```java
public interface DaeColumnRepository extends ReactiveNeo4jRepository<DaeColumnNode, String> {

}
```

Create controller

```java
@RestController
@RequestMapping("/column")
public class DaeColumnController {

	private final DaeColumnRepository columnRepository;

	public DaeColumnController(DaeColumnRepository columnRepository) {
		this.columnRepository = columnRepository;
	}

	@PostMapping("/save")
	public Mono<DaeColumnNode> save(@RequestBody DaeColumnNode node){
		return columnRepository.save(node);
	}

	@PostMapping("/save/all")
	public Flux<DaeColumnNode> saveAll(@RequestBody List<DaeColumnNode> nodes){
		return columnRepository.saveAll(nodes);
	}
}
```

Run

```java
curl --location --request POST 'localhost:8080/column/save' \
--header 'Content-Type: application/json' \
--data-raw '{
    "daeId": "123-abc",
    "labels": [
        "Column",
        "Test",
        "Model"
    ]
}'
```

and

```java
curl --location --request POST 'localhost:8080/column/save/all' \
--header 'Content-Type: application/json' \
--data-raw '[
    {
        "daeId": "987-zyx",
        "labels": [
            "Column",
            "Test",
            "Model"
        ]
    }
]'
```

Run cypher query

```
MATCH (n:Column) RETURN n, labels(n) LIMIT 25
```

that returns

```java
╒═══════════════════╤═════════════════════════╕
│"n"                │"labels(n)"              │
╞═══════════════════╪═════════════════════════╡
│{"daeId":"123-abc"}│["Column","Test","Model"]│
├───────────────────┼─────────────────────────┤
│{"daeId":"987-zyx"}│["Column"]               │
└───────────────────┴─────────────────────────┘
```

---

**Affects:** 6.0 M2 (2020.0.0)

**Reference URL:** https://github.com/neo4j/sdn-rx/issues/272

**Comment by michael-simons** [comment] 2021-01-15 12:21
This is a duplicate of #2110.

**Closed by michael-simons** 2021-01-15 12:21 UTC
Labels: status: duplicate, type: bug
