### ISSUE TITLE
Query loads entities in excessive depth, which are not accessible by the projection.

### ISSUE THREAD

**Issue by Andy2003** [spring-projects/spring-data-neo4j#2373] opened 2021-09-06 08:15 UTC
To prevent loading the whole database in memory, I tried to use projection interfaces. But this is not preventing spring-data-neo4j to load all the relations behind the scenes.

Given:

Data:

```cypher
CREATE (root:Node:BaseNodeEntity{nodeId: 'root'})
CREATE (company:Node:BaseNodeEntity{nodeId: 'comp'})
CREATE (location1:Node:BaseNodeEntity{nodeId: 'location1'})
CREATE (location2:Node:BaseNodeEntity{nodeId: 'location2'})

CREATE (meter1:MeasurementMeta:BaseNodeEntity{nodeId: 'meter1'})
CREATE (meter2:MeasurementMeta:BaseNodeEntity{nodeId: 'meter2'})

CREATE (meter1)-[:CHILD_OF]->(location1)
CREATE (meter2)-[:CHILD_OF]->(location2)
CREATE (location1)-[:CHILD_OF]->(company)
CREATE (location2)-[:CHILD_OF]->(company)
CREATE (company)-[:CHILD_OF]->(root)
```

Entities:

```java
@Node
@NonFinal
@Data
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class BaseNodeEntity {
	@Id
	@GeneratedValue(GeneratedValue.UUIDGenerator.class)
	@EqualsAndHashCode.Include
	String nodeId;

	@Relationship(type = "CHILD_OF", direction = OUTGOING)
	BaseNodeEntity childOf;
}
```

```java
@org.springframework.data.neo4j.core.schema.Node
@Data
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class Node extends BaseNodeEntity {
	@Relationship(type = "CHILD_OF", direction = INCOMING)
	protected Set<BaseNodeEntity> childNodes;
}
```

```java
@org.springframework.data.neo4j.core.schema.Node
@Data
@EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true)
public class MeasurementMeta extends BaseNodeEntity {
}
```

Projection interfaces:

```java
interface NodeWithoutChild {
	String getNodeId();
}
```

```java
interface NodeWithChild extends NodeWithoutChild {
	Set<NodeWithoutChild> getChildNodes();
}
```

Repository:

```java
public interface BaseNodeRepository<T extends BaseNodeEntity> extends Neo4jRepository<T, String> {
	<R> Optional<R> findNodeByNodeId(String nodeId, Class<R> clazz);
}
```

Invocation

```java
repository.findNodeByNodeId("root", NodeWithChild.class);
```

Results in the following db queries:

```
RUN "MATCH (baseNodeEntity:`BaseNodeEntity`) WHERE baseNodeEntity.nodeId = $0 WITH collect(id(baseNodeEntity)) AS __sn__ RETURN __sn__" {0="root"} {}

RUN "MATCH (baseNodeEntity:`BaseNodeEntity`) WHERE baseNodeEntity.nodeId = $0 OPTIONAL MATCH (baseNodeEntity)<-[__sr__:`CHILD_OF`]-(__srn__:`BaseNodeEntity`) WITH collect(id(baseNodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__" {0="root"} 

RUN "MATCH (baseNodeEntity:`BaseNodeEntity`) WHERE id(baseNodeEntity) IN $__ids__ OPTIONAL MATCH (baseNodeEntity)<-[__sr__:`CHILD_OF`]-(__srn__:`BaseNodeEntity`) WITH collect(id(baseNodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__" {__ids__=[1]} 

RUN "MATCH (baseNodeEntity:`BaseNodeEntity`) WHERE id(baseNodeEntity) IN $__ids__ OPTIONAL MATCH (baseNodeEntity)<-[__sr__:`CHILD_OF`]-(__srn__:`BaseNodeEntity`) WITH collect(id(baseNodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__" {__ids__=[2, 3]} 

RUN "MATCH (baseNodeEntity:`BaseNodeEntity`) WHERE id(baseNodeEntity) IN $__ids__ OPTIONAL MATCH (baseNodeEntity)<-[__sr__:`CHILD_OF`]-(__srn__:`BaseNodeEntity`) WITH collect(id(baseNodeEntity)) AS __sn__, collect(id(__srn__)) AS __srn__, collect(id(__sr__)) AS __sr__ RETURN __sn__, __srn__, __sr__" {__ids__=[4, 5]} 

RUN "MATCH (rootNodeIds) WHERE id(rootNodeIds) IN $rootNodeIds OPTIONAL MATCH ()-[relationshipIds]-() WHERE id(relationshipIds) IN $relationshipIds OPTIONAL MATCH (relatedNodeIds) WHERE id(relatedNodeIds) IN $relatedNodeIds WITH rootNodeIds AS baseNodeEntity, collect(DISTINCT relationshipIds) AS __sr__, collect(DISTINCT relatedNodeIds) AS __srn__ RETURN baseNodeEntity AS __sn__, __sr__, __srn__" {rootNodeIds=[0], relatedNodeIds=[1, 2, 3, 4, 5], relationshipIds=[0, 1, 2, 3, 4]}
```

As you can see the library traverses the whole graph down to the measurements, even if only one level is projected.

Code: https://github.com/Andy2003/spring-data-neo4j/tree/to-many-loadings

**Comment by meistermeier** [comment] 2021-09-08 14:47
The issue is related to #2320 .
In general this should not create a query cascade at all but only fetch the root `NodeWithChild` node. The `NodeWithoutChild` relationship already refers to the same (entity) class and should tell SDN not to reach any further. I think due to the inheritance in the projection, you managed to
a) form the cycle and the limitation for cycles kicks in on projection class parsing correctly. I can only see `nodeId` and `childNodes` in the requested list.
but also b) that the query creation logic thinks that there is still a cycle.

I would like to revisit first the #2320 work that needs to be done instead of just fixing the query creation by limiting the possible mapping even more. If this is too much work in relation to fix this problem here, I would fix this problem first.

**Comment by meistermeier** [comment] 2021-09-16 19:45
I merged now the feature for cyclic projection mapping.
This would mean that this issue would not be valid anymore in the sense that it creates a too broad query.
We can keep this open until you can report back on a released version if this fixes the "too many requested data" problem for you.

**Closed** 2021-10-11 07:51 UTC
Labels: type: bug, status: waiting-for-feedback, type: enhancement, status: feedback-reminder
