### ISSUE TITLE
Don't resolve circular possible circular relationships for queries returning count or exists projections.

### ISSUE THREAD

**Issue by martin-salinger** [spring-projects/spring-data-neo4j#2157] opened 2021-02-18 17:11 UTC
Hi,

with version 6.0.4 and 6.0.5 a derived count query like
`long countByLastname(String lastname);`
throws an AopInvocationException:
`org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type`

The reason is an incorrectly generated cypher query:
`MATCH ... WITH collect(id(n)) AS __sn__ RETURN __sn__`

With version 6.0.3 (and before) the cypher query is generated correctly:
`MATCH ... RETURN count(*)`

BTW: Thanks a lot for the great work!

**Comment by michael-simons** [comment] 2021-02-18 17:26
I can confirm this bug.

**Comment by michael-simons** [comment] 2021-02-18 21:39
This will be fixed in the next patch. 

We are sorry for causing you issues. The root cause is to be related in the much improved querying of cycling mapping, which get's triggered by your mapping. 

To mitigate the issue, you can use 

```
@Query(value = "MATCH (n:Label {lastname: $lastname}) RETURN count(n)", count = true)
long countByLastname(String lastname);
```

or 

```
@Query(value = "MATCH (n:Label {lastname: $lastname}) RETURN count(n) > 0", exists = true)
long existByLastname(String lastname);
```

(`exists` being affected as well).

**Comment by martin-salinger** [comment] 2021-02-19 08:33
Thank you for the custom query to mitigate the issue!

It´s good to hear that the querying of cycling mapping has been much improved  :thumbsup:

**Closed** 2021-02-19 17:56 UTC
Labels: type: bug
